## [특강] Numpy, Pandas, Matplotlib

### 1. Numpy: 고속 연산, 슬라이싱 및 차원 제어
#### 1.1 명시적 타입 배열 생성과 다차원 슬라이싱

In [12]:
import numpy as np

nums = np.array([10, 20, 30], dtype=np.float64) # 1차원 배열 -> Vector
nums # array([10, 20, 30])

array([10., 20., 30.])

In [ ]:
matrix = np.array([
    [10, 20, 30], 
    [40, 50 ,60],
    [70, 80, 90]
]) # 2차원 배열 -> Matrix

print(matrix)
# [[10 20 30]
#  [40 50 60]
#  [70 80 90]]

# 3차원 이상의 배열 Tensor

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [14]:
print('0행 2열 :' , matrix[0][2], matrix[0, 2])

0행 2열 : 30 30


In [17]:
mat = matrix[0:2, 1:3] # 행 -> 0 ~ 1, 열 -> 1, 2
print(mat[0,0])

20


In [18]:

    print(matrix[:, 0])

    print(matrix[1:, :2])

[10 40 70]
[[40 50]
 [70 80]]


#### 1.2 차원 변경(reshape, flatten)과 축(Axis)

reshape(행, 열) / flatten()

In [ ]:
arr = np.arange(1, 13)
print(arr) # [ 1  2  3  4  5  6  7  8  9 10 11 12]

[ 1  2  3  4  5  6  7  8  9 10 11 12]


축(axis)

In [ ]:
mat_3x4 = arr.reshape(3, 4)
print(mat_3x4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print(arr.reshape(4, -1))
# [[ 1  2  3]
#  [ 4  5  6]
#  [ 7  8  9]
#  [10 11 12]]b

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
flat_arr = mat_3x4.flatten()
print(flat_arr) # [ 1  2  3  4  5  6  7  8  9 10 11 12]

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
mat = np.arange(1, 7).reshape(2, -1)
print(mat)

sum_axis0 = mat.sum(axis=0)
sum_axis1 = mat.sum(axis=1)
print(f'axis0 행 기준 합계: {sum_axis0}') # axis0 행 기준 합계: [5 7 9]
print(f'axis1 열 기준 합계: {sum_axis1}') # axis1 열 기준 합계: [ 6 15]
b

[[1 2 3]
 [4 5 6]]
axis0 행 기준 합계: [5 7 9]
axis1 열 기준 합계: [ 6 15]


#### 1.3 Numpy 브로드캐스팅(Broadcasting) 연산

In [ ]:
mat = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print(mat * 5)
# [[ 50 100 150]
#  [200 250 300]]

print(mat + 5)
# [[15 25 35]
#  [45 55 65]]

vec = np.array([1, 2, 3])
print(mat + vec)
# 각 행에 vec 요소 값이 더해짐
# [[11 22 33]
#  [41 52 63]]

[[ 50 100 150]
 [200 250 300]]
[[15 25 35]
 [45 55 65]]


In [ ]:
vec = np.array([1, 2, 3])
print(mat + vec)
# 각 행에 vec 요소 값이 더해짐
# [[11 22 33]
#  [41 52 63]]

[[11 22 33]
 [41 52 63]]


#### 1.4 행렬 전치(Transpose) 및 행렬곱(@)

In [ ]:
mat = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(mat)
# [[1 2 3]
#  [4 5 6]]

print(mat.transpose())
# [[1 4]
#  [2 5]
#  [3 6]]

print(mat.T)
# [[1 4]
#  [2 5]
#  [3 6]]

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


In [40]:
mat1 = np.array([ [10, 20], [30, 40] ])
mat2 = np.array([[1, 2], [3, 4]])

mat3 = mat1 @ mat2
print(mat3)
# [[ 70 100]
#  [150 220]]

[[ 70 100]
 [150 220]]
